export enum SPORT_TYPES {
  Soccer = 'Soccer',
  Basketball = 'Basketball',
  Baseball = 'Baseball',
  Football = 'Football',
  Tennis = 'Tennis',
  Volleyball = 'Volleyball',
  Cricket = 'Cricket',
  Hockey = 'Hockey',
  Rugby = 'Rugby',
  TableTennis = 'Table Tennis',
  Badminton = 'Badminton',
  Golf = 'Golf',
  Softball = 'Softball',
  Lacrosse = 'Lacrosse',
  UltimateFrisbee = 'Ultimate Frisbee',
  Track = 'Track',
  Swimming = 'Swimming',
  Wrestling = 'Wrestling',
  Rowing = 'Rowing',
  FieldHockey = 'Field Hockey',
  Other = 'Other',
}
